from __future__ import annotations

from typing import Any


class QualityService:
    """Calculate a transparent data-quality score from an ingestion run."""

    WEIGHTS = {
        "completeness": 0.35,
        "uniqueness": 0.25,
        "validity": 0.25,
        "readiness": 0.15,
    }

    @staticmethod
    def calculate(
        pipeline_run: dict[str, Any],
        dataset_rows: int,
    ) -> dict[str, Any]:
        """
        Calculate data-quality metrics from existing pipeline metadata.

        This service does not revalidate or modify the dataset. It reuses
        validation results already generated by the ingestion pipeline.
        """
        original_rows = max(
            int(pipeline_run.get("original_rows", 0)),
            0,
        )

        ready_rows = max(
            int(pipeline_run.get("ready_rows", 0)),
            0,
        )

        quarantined_rows = max(
            int(pipeline_run.get("quarantined_rows", 0)),
            0,
        )

        validation_report = pipeline_run.get(
            "validation_report",
            {},
        )

        if not isinstance(validation_report, dict):
            validation_report = {}

        missing_values = validation_report.get(
            "missing_values",
            {},
        )

        if not isinstance(missing_values, dict):
            missing_values = {}

        missing_value_count = sum(
            int(value)
            for value in missing_values.values()
            if isinstance(value, (int, float))
            and value >= 0
        )

        duplicate_row_count = QualityService._non_negative_int(
            validation_report.get(
                "exact_duplicate_rows",
                0,
            )
        )

        duplicate_task_id_count = QualityService._non_negative_int(
            validation_report.get(
                "duplicate_task_id_rows",
                0,
            )
        )

        completeness_score = (
            QualityService._completeness_score(
                original_rows=original_rows,
                missing_value_count=missing_value_count,
            )
        )

        uniqueness_score = (
            QualityService._uniqueness_score(
                original_rows=original_rows,
                duplicate_count=(
                    duplicate_row_count
                    + duplicate_task_id_count
                ),
            )
        )

        if original_rows == 0:
            validity_score = 0.0
        else:
            validity_score = QualityService._validity_score(
                validation_report=validation_report,
            )

        readiness_score = QualityService._percentage(
            numerator=ready_rows,
            denominator=original_rows,
        )

        quality_score = round(
            (
                completeness_score
                * QualityService.WEIGHTS["completeness"]
            )
            + (
                uniqueness_score
                * QualityService.WEIGHTS["uniqueness"]
            )
            + (
                validity_score
                * QualityService.WEIGHTS["validity"]
            )
            + (
                readiness_score
                * QualityService.WEIGHTS["readiness"]
            ),
            2,
        )

        quarantine_rate = QualityService._percentage(
            numerator=quarantined_rows,
            denominator=original_rows,
        )

        issues = QualityService._issues(
            validation_report=validation_report,
            quarantined_rows=quarantined_rows,
            quarantine_rate=quarantine_rate,
        )

        return {
            "quality_score": quality_score,
            "grade": QualityService._grade(quality_score),
            "metrics": {
                "completeness_score": completeness_score,
                "uniqueness_score": uniqueness_score,
                "validity_score": validity_score,
                "readiness_score": readiness_score,
                "quarantine_rate": quarantine_rate,
            },
            "summary": {
                "original_rows": original_rows,
                "ready_rows": ready_rows,
                "quarantined_rows": quarantined_rows,
                "dataset_rows": max(
                    int(dataset_rows),
                    0,
                ),
                "missing_value_count": missing_value_count,
                "duplicate_row_count": duplicate_row_count,
                "duplicate_task_id_count": (
                    duplicate_task_id_count
                ),
            },
            "issues": issues,
        }

    @staticmethod
    def _completeness_score(
        original_rows: int,
        missing_value_count: int,
    ) -> float:
        if original_rows == 0:
            return 0.0

        score = 100.0 - (
            missing_value_count
            / original_rows
            * 100.0
        )

        return round(
            max(score, 0.0),
            2,
        )

    @staticmethod
    def _uniqueness_score(
        original_rows: int,
        duplicate_count: int,
    ) -> float:
        if original_rows == 0:
            return 0.0

        score = 100.0 - (
            duplicate_count
            / original_rows
            * 100.0
        )

        return round(
            max(score, 0.0),
            2,
        )

    @staticmethod
    def _validity_score(
        validation_report: dict[str, Any],
    ) -> float:
        score = 100.0

        if validation_report.get(
            "missing_columns"
        ):
            score -= 40.0

        if validation_report.get(
            "required_field_errors"
        ):
            score -= 30.0

        if validation_report.get(
            "unexpected_columns"
        ):
            score -= 10.0

        if validation_report.get(
            "duplicate_task_id_rows",
            0,
        ):
            score -= 20.0

        return round(
            max(score, 0.0),
            2,
        )

    @staticmethod
    def _issues(
        validation_report: dict[str, Any],
        quarantined_rows: int,
        quarantine_rate: float,
    ) -> list[dict[str, Any]]:
        issues: list[dict[str, Any]] = []

        missing_columns = validation_report.get(
            "missing_columns",
            [],
        )

        if missing_columns:
            issues.append(
                {
                    "type": "missing_columns",
                    "severity": "high",
                    "count": len(missing_columns),
                    "message": (
                        "Expected columns are missing."
                    ),
                    "details": missing_columns,
                }
            )

        required_field_errors = (
            validation_report.get(
                "required_field_errors",
                {},
            )
        )

        if required_field_errors:
            issues.append(
                {
                    "type": "required_field_errors",
                    "severity": "high",
                    "count": len(
                        required_field_errors
                    ),
                    "message": (
                        "Required fields contain "
                        "invalid or missing data."
                    ),
                    "details": required_field_errors,
                }
            )

        duplicate_task_id_count = (
            QualityService._non_negative_int(
                validation_report.get(
                    "duplicate_task_id_rows",
                    0,
                )
            )
        )

        if duplicate_task_id_count:
            issues.append(
                {
                    "type": "duplicate_task_ids",
                    "severity": "high",
                    "count": duplicate_task_id_count,
                    "message": (
                        "Duplicate business keys "
                        "were detected."
                    ),
                }
            )

        if quarantined_rows:
            severity = (
                "high"
                if quarantine_rate >= 20.0
                else "medium"
            )

            issues.append(
                {
                    "type": "quarantined_rows",
                    "severity": severity,
                    "count": quarantined_rows,
                    "message": (
                        f"{quarantine_rate:.1f}% of input "
                        "rows were quarantined for review."
                    ),
                }
            )

        return issues

    @staticmethod
    def _grade(score: float) -> str:
        if score >= 90.0:
            return "A"

        if score >= 80.0:
            return "B"

        if score >= 70.0:
            return "C"

        if score >= 60.0:
            return "D"

        return "F"

    @staticmethod
    def _percentage(
        numerator: int,
        denominator: int,
    ) -> float:
        if denominator == 0:
            return 0.0

        percentage = (
            numerator
            / denominator
            * 100.0
        )

        return round(
            min(percentage, 100.0),
            2,
        )

    @staticmethod
    def _non_negative_int(
        value: Any,
    ) -> int:
        if not isinstance(value, (int, float)):
            return 0

        return max(
            int(value),
            0,
        )